apiVersion: apps/v1
kind: Deployment
metadata:
  name: serper-search
  namespace: mcp-servers
  labels:
    app: serper-search
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serper-search
  template:
    metadata:
      labels:
        app: serper-search
        version: v1
    spec:
      containers:
      - name: serper-search
        image: shgsousa/serper-search:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: SERPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: serper-search-secret
              key: SERPER_API_KEY
        - name: MCP_HTTP_MODE
          valueFrom:
            configMapKeyRef:
              name: serper-search-config
              key: MCP_HTTP_MODE
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
